# STT E2E Insights Configuration
gcp:
  # project_id will be obtained implicitly from GCP environment
  service_account_key_path: "path/to/service-account-key.json"  # Optional if using default credentials

# Google Cloud Storage Configuration
gcs:
  input_bucket: "pg-transcript"
  output_bucket: "pg-transcript"
  input_folder: "audio-files/"
  output_folder: "processed-conversations/"
  file_prefix_filter: "merged"  # Only process files starting with this prefix

# Data Loss Prevention (DLP) Configuration
dlp:
  location: "us-central1"
  identify_template_id: "identify"  # Template name only, project will be auto-detected
  deidentify_template_id: "deidentify"  # Template name only, project will be auto-detected
  # Context-aware inspection for better accuracy
  include_quote: true
  
# Contact Center AI Insights Configuration
ccai:
  location: "us-central1"
  recognizer_id: "ccai-insights-recognizer"  # Recognizer name for direct audio ingestion
  conversation_ttl_days: 365
  # Conversation metadata
  agent_id: "agent-001"
  
  # Channel configuration for audio ingestion
  # Standard convention: customer=1, agent=2 (modify if your setup differs)
  customer_channel: 1
  agent_channel: 2
  
  # Note: For IngestConversations API to work, you need:
  # 1. A Speech recognizer created in the same project/location
  # 2. Project number (not project ID) in the recognizer path
  # 3. Proper IAM permissions:
  #    - contactcenterinsights.conversations.create
  #    - contactcenterinsights.conversations.ingest
  #    - storage.objects.get
  #    - storage.objects.list
  # 4. The recognizer must be in ACTIVE state
  customer_id: "customer-001"
  
# Processing Configuration
processing:
  max_concurrent_files: 5
  retry_attempts: 3
  retry_delay_seconds: 2
  chunk_size_mb: 10  # For large file processing

# Logging Configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/stt_insights.log"